### ISSUE TITLE
Local classes that follow a global pseudo class are incorrectly global

### ISSUE THREAD

**Issue by Ryan-McMillan** [tivac/modular-css#131]
`:global(.preview) .balances` results in `.preview .balances`.  It should be `.preview .mca3c0d3e3_balances`.

It's worth noting that anything before the global pseudoclass is local(as expected).  `.balances :global(.preview)` results in `.mca3c0d3e3_balances .preview`.

**Comment by tivac** [comment]
Oof, thanks. I'll dig into it and see what might be going wrong.
