### ISSUE TITLE
Imports not handled correctly

### ISSUE THREAD

**Issue by r24y** [tivac/modular-css#142]
When a stylesheet imports from a URL, the output inlines the `@import` incorrectly in the middle of the stylesheet, depending on the order in which the compiler decided to concatenate the input files.

Per [`@import` spec](https://www.w3.org/TR/css-cascade-3/#at-import):

> Any `@import` rules must precede all other at-rules and style rules in a style sheet (besides `@charset`, which must be the first thing in the style sheet if it exists), or else the `@import` rule is invalid.

**Comment by tivac** [comment]
Yeah, we don't ship `@import` rules in production because of performance concerns so there's no code to handle that. I'd accept a PR for adding logic to track those statements and inject them at the beginning of the output, but I'm not really convinced that it's a common need.

**Comment by r24y** [comment]
Sounds good. Flag, maybe? (Something like `--inject-imports`)

**Comment by tivac** [comment]
Sorry, i had a change of heart.


Thinking about this more and it should probably just be a postcss plugin run as part of the `done` lifecycle hook. Unless more folks come along asking for it I don't really want to add more complexity to the core.

**Comment by r24y** [comment]
Ah, good. That sounds more appropriate.
