### ISSUE TITLE
Bug with composing a global class with a non-global class of the same name.

### ISSUE THREAD

**Issue by ctcleary** [tivac/modular-css#184]
In a .css file to be processed by modular-css:

```
.icon-bg {
    composes: global(icon-bg);

   color: red;
}
```

- In this case, `color: red;` being a stand-in for something you'd actually want to do.
- Encountered while using the `rollup` plugin, if that helps.

The error I get in the console when I try to `modular-css`ify that in the rollup build:

```
{ [Error: Error transforming [[FILE_PATH]]\pagestyle.css with 'modular-css' plugin: Dependency Cycle Found: icon-bg -> icon-bg]
  rollupTransform: true,
  id: '[[FILE_PATH]]\\pagestyle.css',
  plugin: 'modular-css' }
```

**Comment by tivac** [comment]
Fixed in `0.27.1` which is on NPM now.
