### ISSUE TITLE
Paths are case sensitive and can result in duplicate css with different hashes

### ISSUE THREAD

**Issue by Ryan-McMillan** [tivac/modular-css#191]
I ran into the generated file having duplicate entries from the same file.  The paths appear to be case-sensitive.

If I have two compose statements cased incorrectly like these:

> composes: serif from "../../../../../services/Js2Commerce/public/gw2.css";
> composes: serif from "../../../../../services/js2commerce/public/gw2.css";

I'll have 3 copies of gw2.css in the gen file.  One for each of these and another from the js that has it cased differently.   They all have different hashes for the classnames.  Not sure if it's worth noting, but the path from js has lowercase _public_, even though the directory is uppercase.

**Comment by tivac** [comment]
I don't see a great way to solve this. I can make it be case-insensitive internally but that will have problems on case-sensitive file systems. I could say "that's user error" but that seems needlessly harsh as well.

May be worth looking into `fs.lstat` at some point and using inodes but that's gonna be a big re-working and doesn't necessarily seem worth it right now.

**Comment by tivac** [comment]
Did this work in the [`issues/191`](https://github.com/tivac/modular-css/tree/issues/191) branch. Will need to find some time to get this committed.
