### ISSUE TITLE
Server rendering?

### ISSUE THREAD

**Issue by chielkunkels** [tivac/modular-css#201]
Hi there, I'm currently evaluating various css modules packages (to be used with rollup) and came across your excellent-looking module.

Since we're building an isomorphic (or universal, whatever floats your boat) application, I was wondering how to handle server rendering? Obviously we'd use the require extensions in order to catch css files, but I was wondering how to implement this.

In the past I've used a browserify module which would output a json file with all filenames + generated class names so naming would be consistent across client and server side, but I've not seen such a thing in this module (looking through the api and such)

Is the unique slug in the namer function built from a hash of the file name or so? Cause in that case I can get the generated css classes from that, and simply run that on server side?

**Comment by chielkunkels** [comment]
Sorry, I just noticed actually that the CLI has an option to output a JSON file - is this option also available when using the rollup plugin?

**Comment by tivac** [comment]
Sorry about that, I was being a baddie and hadn't kept the rollup docs up-to-date. Should be all updated now.

To directly your question: you can set a [`json`](https://github.com/tivac/modular-css/blob/master/docs/rollup.md#json) option when configuring the rollup plugin and it'll plop out a JSON file on disk that looks like this:

```js
{
    "path/to/file.css": {
        "selector1" : "123abcd_other 123abcd_selector",
        "selector2" : "321cba_selector2",
        // ...
    },
    // ...
}
```

Hopefully that helps!

**Comment by chielkunkels** [comment]
I had actually read through the code and already found the option, but I'd forgotten to reply here. Thanks very much for this great package!
