### ISSUE TITLE
Investigate reducing duplication

### ISSUE THREAD

**Issue by tivac** [tivac/modular-css#219]
https://github.com/css-modules/css-modules/issues/193 & https://github.com/css-modules/css-modules/issues/181 both posit interesting (& similar) ideas for how to reduce total stylesheet size by taking advantage of composition.

This seems like a worthwhile thing to write as a standalone PostCSS plugin, but I'm adding it here so I remember to keep tabs on it.

**Comment by pygy** [comment]
Compiling to atomic CSS does reduce the sheet size, but

- it meshes badly with complex selectors (e.g. `.foo.bar`) 
- it is  subject to remote cascading effects. Suppose you have 

```CSS
.foo [
  margin-left: 20px
}
.bar [
  margin: 10px;
  margin-left: 20px
}
```

It will become
```CSS
.mrg-lft-20 [
  margin-left: 20px
}
.mrg-10 [
  margin: 10px;
}
// foo = "mrg-lft-20"
//.bar = "mrg-lft-20 mrg-10" => boom even if the names are swapped, the definition order wins.
```

- it looks like a nightmare to debug.

**Comment by tivac** [comment]
Closing this out for now, I won't have the time to chase this down in the near future.
