### ISSUE TITLE
Non-watchify file watchers put you in cache hell

### ISSUE THREAD

**Issue by Morklympious** [tivac/modular-css#226]
Hey Pat! 

Ran into an issue with Modular-CSS processing CSS dependencies when coding up something recently. 
I'm using [Browser-sync](https://www.browsersync.io/), which has it's own standalone file watching system (pretty fun if you haven't checked it already), so I end up glob matching on the `src/` directory and listen for any changes, like so:

```js
/**
 * Initializing over the dist directory, with a delay that will allow for rapid
 * src directory file changes in case some smoking gun can't keep their fingers
 * off of the ctrl+s combo
 *
 * ... I'm talking of course, about myself.
 */
sync.init({
  server: "./dist",
  reloadDelay: 1500
});

/**
 * Let's go ahead and just watch the entirety of the source directory
 * (Thanks for standalone file watching, browser-sync!)
 *
 * If there are any changes on our non-entry.js files, we'll hot reload.
 * Browserify will handle entry.js and tell Browser-sync to reload whenever
 * Browserify bundles.
 */
sync.watch("./src/**/*.*").on("change", () => {
  build.copy(); // Copy non-build related files
  build.bundle(); // Browserify and output CSS + JS
});
```

In pretty much every case, I rebundle my browserify bundle, and since I'm using Modular-CSS as a plugin, I'm expecting that running the bundle function will give me an updated CSS file in `./dist/css/site.css`:

```js
// . . .

builder.plugin("modular-css/browserify", {
  css : "./dist/css/site.css",

  after: [
    require("postcss-import")
  ]
});

// . . . 


function _bundle() {
    var write = fs.writeFileSync;

    builder.bundle(function(err, output) {
      if(err) {
        console.log(err);
        return;
      }

      write("./dist/js/bundle.js", output);
    });

}

// . . . 

module.exports = {
  bundle: _bundle
  // . . .
}
```

However, it looks like using a file watcher that _isn't_ `Watchify` causes the Modular-CSS plugin to not purge its file cache. For the life of my Browser-sync watcher, any file modification and subsequent rebundle would output the same global CSS file (despite containing changes in src). Looks like the plugin runs but it doesn't remove existing files unless the events that Watchify fired are... fired. After some debugging, I found The offending block of code:

```js 
// Watchify fires update events when files change, this tells the processor
// to remove the changed files from its cache so they will be re-processed
browserify.on("update", function(files) {
    processor.remove(files);
});
```
This was essentially solved after I re-included `watchify` into my single-build file, but it seems like redundancy especially if I don't necessarily want to be tied to watchify and want to use some other file watcher less specific to Browserify. 

I'm wondering if there's a way to just fire off, refactor, or spoof this workflow because you get stuck in cache hell if you don't use watchify.  Or maybe the solution is to pass in an option that disables the cache. 

I'm pretty sure this doesn't affect a majority of users, but it's a fun edge case.

**Comment by tivac** [comment]
Makes sense, the underlying `Processor` instance caches files to prevent duplicating effort but that falls over when you don't have access to that cache.

Easiest solution right now would be to either re-init your browserify bundler on file change (:unamused:) or see if you can remove/re-add the plugin on file change (:cry:)

I can look into exposing the underlying `Processor` instance onto the bundler itself, but that feels like a real weird API. I freely admit that my head's way out of the browserify game though so maybe there's a better solution that I'm just not thinking of.

Sidenote: The `Processor` instance doesn't currently *have* a way to disable the caching, because of course I didn't think it needed that. Oops 😒

**Comment by Morklympious** [comment]
In the meantime, I've found a workaround which is basically separating single-build vs. watch-then-build logic. 

In the single build, attaching the `modular-css/browserify` plugin so it can output hashed CSS on bundle is fine, since it's not a polling or watching process. 

```js
var fs          = require('fs'),
    shell       = require('shelljs'),
    browserify  = require('browserify'),
    watchify    = require("watchify");

var builder = browserify("./src/js/entry.js", {
  debug: false
});

builder.plugin("modular-css/browserify", {
  css: "./dist/css/site.css",

  after: [
    require("postcss-import")
  ]
});

// ...

```

In the watching file (again, using Browser-sync), Setting the plugin to watchify is fine enough so that it can emit the `update` event. 

```js
var fs     = require("fs"),
    path   = require("path"),
    shell  = require("shelljs"),
    sync   = require("browser-sync").create(),
    build  = require("./build-default.js"),

    // Including debounce so we don't refresh 15000 times whenever the
    // dist directory changes
    debounce = require("lodash.debounce");

build.builder.plugin("watchify");
build.builder.on("update", build.bundle);

// . . . 

sync.watch("./src/**/*.*").on("change", () => {
  build.copy();
});

sync.watch("./src/js/**/*.js").on("change", () => {
  build.bundle();
});

sync.watch("./src/css/**/*.css").on("change", () => {
  build.bundle();
});

/**
 * In the event that anything in dist changes (by some third party build magic)
 * then we'll just refresh the whole shebang.
 */
sync.watch("./dist/**/*.*").on("change", debounce(sync.reload, 750));

```

It looks like as long as bundle is a one-time op you can call it with abandon. The only real overhead is that I have duplicate file watchers that essentially perform the same thing. It's a race condition, but in this case it doesn't matter which goes first since they both bundle the same thing. 

Not elegant, but better than reinitializing the plugin / removing and re-adding every single time. This is also known as the "IT LOOKS LIKE IT WORKS OH GOD I'LL TAKE IT. I'LL TAKE IT TO THE BANK" principle.

**Comment by tivac** [comment]
You can pass `cache: false` in the JS args or `--no-cache` on the CLI to prevent the built-in file caching behavior in `modular-cssify@4.2.0`, which should solve your problem.

**Comment by Morklympious** [comment]
Yesssss. 

Next time I use browser sync in conjunction I will THRIVE INSTEAD OF FLOUNDER. 
Thanks, Pat!
