### ISSUE TITLE
Resolving wrong file

### ISSUE THREAD

**Issue by chielkunkels** [tivac/modular-css#246]
I've been using modular-css with a lot of joy lately, but there's an issue that keeps popping up: modular-css resolves to different files than I'd expect due to it using node's file resolving.

In most cases this is definitely the right approach, but in the context of rollup it can lead to confusion. I'm using `rollup-plugin-include-paths` and `rollup-plugin-node-resolve` roughly like this:

```
	includePaths({
		extensions: ['.css', '.js', '.jsx'],
		paths: ['src'],
	}),
	nodeResolve({
		browser: true,
		extensions: ['.js', '.json', '.jsx'],
		jsnext: true,
	}),
```

The "problem" here is that I'd like to search `src` before resorting to the regular node lookup. Is there any way that `modular-css` can be set up in a way that it would fall through the same chain, or is there any way to instruct `modular-css` to search in another directory first?

Thanks for your hard work so far!

**Comment by tivac** [comment]
I was pondering a configurable `resolve` option at some point, but have avoided it so far due to the added complexity that I don't personally need. If you've got an API proposal I'm open to discussing it and figuring out a solution.

**Comment by chielkunkels** [comment]
Sorry for the late reply, but was launching a website so things have been a bit hectic.

I'm not even sure if this is something that modular-css should be fixing, or if I should fix it by structuring my projects differently.

Currently, I have a directory structure that looks a bit like this (React project, very much simplified):

```
src
└── app
    ├── components
    │   └── App.jsx
    └── styles
        └── app.css
```

Then I transpile (with babel) this directory for server-side rendering purposes, and symlink this directory into `node_modules` so I can do lookups such `app/components/App`, rather than having to type `../components/App` and the like.

As a result of this, the resolving mechanism used in modular-css gets files from the `dist` directory rather than the `src` directory if I use absolute paths. I guess I could use relative paths just for the css, or maybe move them out somewhere...

Like you said, adding resolving mechanisms can be a rather hairy ordeal - how do you handle this over at ArenaNet?

**Comment by tivac** [comment]
We use relative paths for CSS, but I think we'd certainly make use of something along these lines too. We use `rollup-plugin-includepaths` fairly often to make reaching deep into shared services and stuff simpler, and I'd like that in `modular-css` as well.

```css
@value gw2Css: "../../../../../../Services/Js2Commerce/public/gw2.css";
```

because that's just silly. So I thought about it a bit and a `rollup`-style resolver array seems reasonable.

```js
new Processor({
    resolvers : [
        (src, file, resolve) => {
            // resolve file here
            // return a string absolute file path or undefined to
            // fall through to the next resolver, with the built-in one
            // acting as a last resort
        }
    ]
})
```

thoughts?

**Comment by tivac** [comment]
@chielkunkels Any feedback? I'll have some time to tackle this later tonight so knowing if the proposal solves your problem would be nice 😄

**Comment by chielkunkels** [comment]
The proposal looks great. A couple things:

- I would maybe rename `src` and `file` to `from` and `to` respectively, since I think it signals the intent a bit better. `resolve` seems good to pass along, especially since you might want to do a default resolve and then do stuff with the result.
- In terms of behaviour, I think you should always return an absolute full path, since you can always just fall back to using the same `resolve` function. If you define this function, I think it makes sense to let the user fully take care of this.

Finally, yes, this proposal definitely solves my problem. I think it will actually fix any possible issue since the user can implement this however they see fit.

Thanks for your effort!

**Comment by tivac** [comment]
Fixed in `modular-css@3.2.0`

**Comment by chielkunkels** [comment]
It never ceases to amaze me how fast you are implementing all my requests - thanks so much for your efforts mate! If we're ever around the same place on the globe I'd love to buy you a beer!

**Comment by tivac** [comment]
:+1: :smile: When you ask for smart things I'd be silly to ignore it!

**Comment by tivac** [comment]
@chielkunkels to close the loop, https://www.npmjs.com/package/modular-css-paths now exists on npm :smile:

**Comment by chielkunkels** [comment]
Oh nice!

I'm also considering making a pull request for the custom class-namer that I made for our website. Basically it ensures that you always use the smallest possible class name. Would that be something you're interested in providing as a part of modular-css (or at least the modular-css ecosystem)?

**Comment by tivac** [comment]
https://www.npmjs.com/package/modular-css-namer is what I made, but I'm all for seeing an implementation that can (safely) go smaller!

**Comment by chielkunkels** [comment]
Hmm, does this generate single letter selectors using all letters of the alphabet, and then move on to two-letter selectors, and so on? aka, first `.a` to `.Z`, then `.aa` to `.aZ` and `.ZZ` then on to `.aaa` to `.ZZZ` and so on? Cause that's the thing that I wrote does.

You can see it in action on the first website where it's being used now: http://poki.cz/ - don't mind the design too much, it's outdated and will be changed in the coming months :D

**Comment by tivac** [comment]
Nope! It does something way more complicated for stupid reasons because I didn't think it through well enough. Stealing that idea in a moment though XD

**Comment by chielkunkels** [comment]
I could just give you the code. :p

**Comment by chielkunkels** [comment]
```js
export default function createClassGenerator(chars) {
	const max = chars.length - 1;
	const idxs = [0];
	let cursor = 0;

	return () => {
		const selector = idxs.map(i => chars[i]).join('');

		if (idxs[idxs.length - 1] < max) {
			idxs[idxs.length - 1]++;
		} else {
			let reset = 0;

			if (idxs[cursor] < max) {
				idxs[cursor]++;
				reset = cursor + 1;
			} else if (idxs.every(n => n === max)) {
				idxs.push(0);
				cursor = idxs.length - 2;
			} else {
				let nextCursor;
				for (let n = cursor - 1; n >= 0; n--) {
					if (idxs[n] < max) {
						nextCursor = n;
						break;
					}
				}

				reset = nextCursor + 1;
				idxs[nextCursor] ++;
				cursor = idxs.length - 2;
			}

			for (let n = reset; n < idxs.length; n++) {
				idxs[n] = 0;
			}
		}

		return selector;
	};
}

const chars = [];
['a', 'A'].forEach(letter => {
	const s = letter.charCodeAt(0);
	for (let i = s; i < s + 26; i++) {
		chars.push(String.fromCharCode(i));
	}
});

const generateClass = createClassGenerator(chars);
const classNameCache = {};

export default function getClassName(file, className) {
	if (!classNameCache[file]) {
		classNameCache[file] = {};
	}

	if (!classNameCache[file][className]) {
		classNameCache[file][className] = generateClass();
	}

	return classNameCache[file][className];
}
```

Obviously, since you have that `alphabet` package in place already, use that rather than the loop that builds up the character set :)

And then you  just specify `getClassName` as the namer as you'd expect.

I had this separated over two files but yeah, enjoy.

**Comment by shoomyth** [comment]
Well, this works when you have simple build process and modular-css instance (api, plugins, etc.) knows about every file. But when you have some build steps, compile styles separately and glue them into single bundle, in this case naming based on filenames hashes will be little safer.

**Comment by tivac** [comment]
@shoomyth Yup! This is 100% designed for the "make the selectors as small as possible" use-case. It's certainly more common in our usage of `modular-css` so it's what I've optimized `modular-css-namer` for.

**Comment by chielkunkels** [comment]
Was thinking about this some more (and this is of course way off topic from the original issue), but one way you could do it is pass a selector cache along which is shared between files, if you want to do splitting of css files. :)
