### ISSUE TITLE
webpack namedExports mode

### ISSUE THREAD

**Issue by TrySound** [tivac/modular-css#280]
Webpack2 has es modules support and can validate existing exports of (!) harmony modules. The module should contain at least one import or export statement.

```js
module.exports = {
    entry: './src/index.js',
    output: {
        filename: 'dist/bundle.js'
    },
    module: {
        strictExportPresence: true
    }
};
```

```
ERROR in ./src/index.js
3:12-23 "export 'namedExport' was not found in './mod.js'
```

Empty output file may contains like this
```js
export const __cssModules__ = true; // export to identify file as harmony contained and enable errors
```
```js
// index.js
import * as style from './myStyle.css';
console.log(style.myClass);
```
```
// myStyle.css
// before
.myClass {}

// after
export const __cssModules = true;
// ... some loading code
export const myClass = 'hash-123456';
```

**Comment by tivac** [comment]
Just to be sure I understand:

You're asking for me to modify the JS output so it does two things:

1. Adds a dummy ES2015 `export` if the file is empty
2. Exposes each individual class as a named `export`

I'm totally fine with that, the rollup plugin already does essentially that exact same thing. The one catch is that I don't know anything about how webpack handles commonjs vs ES Modules. Should the plugin's output include both? Does it matter?

**Comment by TrySound** [comment]
It's not quite matter. It can import from commonjs and require from modules.

**Comment by tivac** [comment]
Ok, cool. Do I otherwise correctly understand your request?

**Comment by TrySound** [comment]
Oh, yeah. Exactly.
