### ISSUE TITLE
Incremental build does not work

### ISSUE THREAD

**Issue by TrySound** [tivac/modular-css#290]
module-css-webpack with any watcher

1. process all files
2. change one classname
3. loader source is changed and passed with .string() to processor
4. result.exports contains classes from previous build

I guess something wrong with cache

**Comment by TrySound** [comment]
I guess the problem is here
https://github.com/tivac/modular-css/blob/master/packages/core/processor.js#L266

Previously added files not processed again even if content is changed.

**Comment by tivac** [comment]
Ugh, sure. I need better webpack tests clearly. Sorry about that, I clearly need to use the webpack implementation more so I notice these sooner.

**Comment by TrySound** [comment]
I guess it's not only about webpack. Every instrument with incremental build can use this. So better run this tests in core package and just pass a few sources with the same identifier.
