### ISSUE TITLE
Class names that are not valid JS identifiers are excluded from Webpack bundle

### ISSUE THREAD

**Issue by kevinkace** [tivac/modular-css#294]
CSS class names are exported differently in a webpack bundle depending if the class names are valid JS identifiers or not. Invalid class names are only included under `.default`.

```css
.thing {
  display: block;
}
.thing-0 {
  display: block;
}
```

```js
(function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "thing", function() { return thing; });
var thing = "mc7c4fa8d1_thing";
/* harmony default export */ __webpack_exports__["default"] = ({
    "thing": "mc7c4fa8d1_thing",
    "thing-1": "mc7c4fa8d1_thing-1"
});

}),
```

Test repo: https://github.com/kevinkace/webpackTest

**Comment by tivac** [comment]
This came about because of the change to ES2015 exports in #282, seems like it's related to https://github.com/webpack/webpack/issues/4742

**Comment by tivac** [comment]
I may need to revert the change to use ES2015 exports, will see which API is more annoying. Having to `require("./file.css").default` to get at all the exports when using `-` in selector names is not-great.

/cc @TrySound as the source of the request for ES2015 exports to hear another perspective.

**Comment by TrySound** [comment]
@kevinkace Using `require().default` is normal as es modules is standard which should be used all the time. Of course with es modules you don't need to access default explicit, just `import style from './style.css';` or better `import * as style from './style.css';`.

Maybe this should be a breaking change, but this is the right way.

**Comment by TrySound** [comment]
@tivac Not a bug. Just two different module systems.

**Comment by TrySound** [comment]
Webpack guys force to use es modules and rewrites loaders with them, so why should we step back?

**Comment by tivac** [comment]
Current plan is to add a `cjs` option to webpack plugin. When truthy the output will be commonjs-style `module.exports` instead of ES2015 modules.

Hoping to get this work completed tonight.

There are plenty of legitimate reasons to still use commonjs, so it needs to be supported in a reasonable & compatible way.

**Comment by TrySound** [comment]
Yeah, it's good, but disabled by default :)

**Comment by tivac** [comment]
This is in `modular-css-webpack@4.4.0`
