### ISSUE TITLE
`webpack --watch` doesn't work with non-named CSS imports

### ISSUE THREAD

**Issue by getkey** [tivac/modular-css#308]
I made a repository at [getkey/modular-css-bug](https://github.com/getkey/modular-css-bug) so you can easily reproduce the bug I was talking about in #291. :-)

Just run `npm run watch` and try to edit `./external.css`. The CSS won't be rebuilt.

**Comment by tivac** [comment]
I just published `modular-css-webpack@5.2.2`, which contains #309 and fixes this problem for me locally. Give it a shot and reopen if you're still seeing the broken behavior!

**Comment by getkey** [comment]
Awesome thanks!
