### ISSUE TITLE
modular-cssify only writing changed files after using watchify update

### ISSUE THREAD

**Issue by darthmaim** [tivac/modular-css#313]
modular-cssify should write the complete css file after a watchify update, but only writes css files that changed (if no css file changed, the written css file is empty). `processor.dependencies()` is only returning changed css files and not all modules like on the first build of the bundle.

This is only broken since version 4, it worked in 3.

**Comment by tivac** [comment]
This is fixed in `modular-cssify@5.1.5`, thanks for the report @darthmaim!
