### ISSUE TITLE
How to properly invalidate/re-process files

### ISSUE THREAD

**Issue by chielkunkels** [tivac/modular-css#324]
Hi Pat, it's me again. I apologise ahead of time for the amount of code etc in this issue, but hopefully it helps.

Due to some requirements in a project I am working on I'm having to split the generation of our css bundles off from the rest of the javascript build. Basically it involves having one css bundle per theme of our websites, and those themes are dynamically loaded based on which site is receiving the request. Boring background information over.

# The setup
So, I am creating my own css bundler for the themes so those get generated independently. The problem I am facing now is that I can't seem to get the processor to properly invalidate the files.

Let's say I have these two files:
```css
/* src/app/styles/themes/default/app.css */
.container {
	background: red;
}
```
```css
/* src/app/styles/themes/default/file.css */
.file {
	color: #fff;
}
```

Generating the initial bundle goes perfectly fine, I get the following output:
```css
/* src/app/styles/themes/default/app.css */
.mc020e1dd7_container {
    background: red
}
/* src/app/styles/themes/default/file.css */
.mc5c717f39_file {
    color: #fff
}
/*# sourceMappingURL=data:application/json;base64,<snip> */
```

Then, if I change the `background` property in `app.css` to yellow:
```
/* src/app/styles/themes/default/app.css */
.container {
	background: yellow;
}
```
 One of two things can happen, depending on the approach.

## Approach one

Just calling `processor.file()` followed by `processor.output()`. It might be me, but this doesn't seem to have any effect at all so I quickly moved on.

## Approach two

First `process.remove()`, then `processor.file()` followed by `processor.output()`. Inspecting the `processor._files` property a couple of things happen:

Before:
```
{ '/Users/chiel/dev/theme-test/src/app/styles/themes/default/app.css':
   { text: '.container {\n\tbackground: red;\n}\n',
     exports: { container: [Object] },
     values: {},
     result:
      Result {
        processor: [Object],
        messages: [Object],
        root: [Object],
        opts: [Object],
        css: '.mc020e1dd7_container {\n\tbackground: red;\n}\n\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9hcHAvc3R5bGVzL3RoZW1lcy9kZWZhdWx0L2FwcC5jc3MiXSwibmFtZX
MiOltdLCJtYXBwaW5ncyI6IkFBQUE7Q0FDQyxnQkFBZ0I7Q0FDaEIiLCJmaWxlIjoic3JjL2FwcC9zdHlsZXMvdGhlbWVzL2RlZmF1bHQvYXBwLmNzcyIsInNvdXJjZXNDb250ZW50IjpbIi5jb250YWluZXIge1xuXHRiYWNrZ3JvdW5kOiByZWQ7XG59XG4iXX0= */',
        map: undefined,
        lastPlugin: [Object] },
     processed:
      LazyResult {
        stringified: true,
        processed: true,
        result: [Object],
        plugin: 8,
        processing: [Object] } },
  '/Users/chiel/dev/theme-test/src/app/styles/themes/default/file.css':
   { text: '.file {\n\tcolor: #fff;\n}\n',
     exports: { file: [Object] },
     values: {},
     result:
      Result {
        processor: [Object],
        messages: [Object],
        root: [Object],
        opts: [Object],
        css: '.mc5c717f39_file {\n\tcolor: #fff;\n}\n\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9hcHAvc3R5bGVzL3RoZW1lcy9kZWZhdWx0L2ZpbGUuY3NzIl0sIm5hbWVzIjpbXSw
ibWFwcGluZ3MiOiJBQUFBO0NBQ0MsWUFBWTtDQUNaIiwiZmlsZSI6InNyYy9hcHAvc3R5bGVzL3RoZW1lcy9kZWZhdWx0L2ZpbGUuY3NzIiwic291cmNlc0NvbnRlbnQiOlsiLmZpbGUge1xuXHRjb2xvcjogI2ZmZjtcbn1cbiJdfQ== */',
        map: undefined,
        lastPlugin: [Object] },
     processed:
      LazyResult {
        stringified: true,
        processed: true,
        result: [Object],
        plugin: 8,
        processing: [Object] } } }
```

After remove:
```
{ '/Users/chiel/dev/theme-test/src/app/styles/themes/default/file.css':
   { text: '.file {\n\tcolor: #fff;\n}\n',
     exports: { file: [Object] },
     values: {},
     result:
      Result {
        processor: [Object],
        messages: [Object],
        root: [Object],
        opts: [Object],
        css: '.mc5c717f39_file {\n\tcolor: #fff;\n}\n\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9hcHAvc3R5bGVzL3RoZW1lcy9kZWZhdWx0L2ZpbGUuY3NzIl0sIm5hbWVzIjpbXSw
ibWFwcGluZ3MiOiJBQUFBO0NBQ0MsWUFBWTtDQUNaIiwiZmlsZSI6InNyYy9hcHAvc3R5bGVzL3RoZW1lcy9kZWZhdWx0L2ZpbGUuY3NzIiwic291cmNlc0NvbnRlbnQiOlsiLmZpbGUge1xuXHRjb2xvcjogI2ZmZjtcbn1cbiJdfQ== */',
        map: undefined,
        lastPlugin: [Object] },
     processed:
      LazyResult {
        stringified: true,
        processed: true,
        result: [Object],
        plugin: 8,
        processing: [Object] } },
  '/Users/chiel/dev/theme-test/src/app/styles/themes/default/app.css':
   { text: '.container {\n\tbackground: yellow;\n}\n',
     exports: false,
     values: {} } }
```
All good, as expected, the file is gone.

After adding the file:
```
{ '/Users/chiel/dev/theme-test/src/app/styles/themes/default/file.css':
   { text: '.file {\n\tcolor: #fff;\n}\n',
     exports: { file: [Object] },
     values: {},
     result:
      Result {
        processor: [Object],
        messages: [Object],
        root: [Object],
        opts: [Object],
        css: '.mc5c717f39_file {\n\tcolor: #fff;\n}\n\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9hcHAvc3R5bGVzL3RoZW1lcy9kZWZhdWx0L2ZpbGUuY3NzIl0sIm5hbWVzIjpbXSw
ibWFwcGluZ3MiOiJBQUFBO0NBQ0MsWUFBWTtDQUNaIiwiZmlsZSI6InNyYy9hcHAvc3R5bGVzL3RoZW1lcy9kZWZhdWx0L2ZpbGUuY3NzIiwic291cmNlc0NvbnRlbnQiOlsiLmZpbGUge1xuXHRjb2xvcjogI2ZmZjtcbn1cbiJdfQ== */',
        map: undefined,
        lastPlugin: [Object] },
     processed:
      LazyResult {
        stringified: true,
        processed: true,
        result: [Object],
        plugin: 8,
        processing: [Object] } },
  '/Users/chiel/dev/theme-test/src/app/styles/themes/default/app.css':
   { text: '.container {\n\tbackground: yellow;\n}\n',
     exports: false,
     values: {} } }
```
So it's back, unprocessed.

And finally after calling `processor.output()`:
```
{ '/Users/chiel/dev/theme-test/src/app/styles/themes/default/file.css':
   { text: '.file {\n\tcolor: #fff;\n}\n',
     exports: { file: [Object] },
     values: {},
     result:
      Result {
        processor: [Object],
        messages: [Object],
        root: [Object],
        opts: [Object],
        css: '.mc5c717f39_file {\n\tcolor: #fff;\n}\n\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9hcHAvc3R5bGVzL3RoZW1lcy9kZWZhdWx0L2ZpbGUuY3NzIl0sIm5hbWVzIjpbXS$
ibWFwcGluZ3MiOiJBQUFBO0NBQ0MsWUFBWTtDQUNaIiwiZmlsZSI6InNyYy9hcHAvc3R5bGVzL3RoZW1lcy9kZWZhdWx0L2ZpbGUuY3NzIiwic291cmNlc0NvbnRlbnQiOlsiLmZpbGUge1xuXHRjb2xvcjogI2ZmZjtcbn1cbiJdfQ== */',
        map: undefined,
        lastPlugin: [Object] },
     processed:
      LazyResult {
        stringified: true,
        processed: true,
        result: [Object],
        plugin: 8,
        processing: [Object] } },
  '/Users/chiel/dev/theme-test/src/app/styles/themes/default/app.css':
   { text: '.container {\n\tbackground: yellow;\n}\n',
     exports: { container: [Object] },
     values: {},
     result:
      Result {
        processor: [Object],
        messages: [Object],
        root: [Object],
        opts: [Object],
        css: '.mc020e1dd7_container {\n\tbackground: yellow;\n}\n\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9hcHAvc3R5bGVzL3RoZW1lcy9kZWZhdWx0L2FwcC5jc3MiXSwibmF
tZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7Q0FDQyxtQkFBbUI7Q0FDbkIiLCJmaWxlIjoic3JjL2FwcC9zdHlsZXMvdGhlbWVzL2RlZmF1bHQvYXBwLmNzcyIsInNvdXJjZXNDb250ZW50IjpbIi5jb250YWluZXIge1xuXHRiYWNrZ3JvdW5kOiB5ZWxsb3c7XG59XG4iXX0= */
',
        map: undefined,
        lastPlugin: [Object] },
     processed:
      LazyResult {
        stringified: true,
        processed: true,
        result: [Object],
        plugin: 8,
        processing: [Object] } } }
```
Still, everything looks as expected.

Upon expecting the result from the `processor.output()` things seem to have gone a bit wonky:
```
Result {
  processor: Processor { version: '5.2.17', plugins: [] },
  messages: [],
  root:
   Root {
     raws: {},
     type: 'root',
     nodes: [ [Object], [Object] ],
     rawCache:
      { commentLeft: ' ',
        commentRight: ' ',
        beforeRule: '\n',
        indent: '    ',
        beforeOpen: ' ',
        semicolon: undefined,
        beforeDecl: '\n',
        colon: ': ',
        beforeClose: '\n' },
     lastEach: 11,
     indexes: {} },
  opts:
   { cwd: '/Users/chiel/dev/theme-test',
     map: true,
     search: 'src/app/styles/themes/default/**/*.css',
     namer: [Function],
     resolvers: [ [Function] ],
     files:
      { '/Users/chiel/dev/theme-test/src/app/styles/themes/default/file.css': [Object],
        '/Users/chiel/dev/theme-test/src/app/styles/themes/default/app.css': [Object] },
     graph:
      { nodes: [Object],
        outgoingEdges: [Object],
        incomingEdges: [Object] },
     resolve: [Function] },
  css: '/* src/app/styles/themes/default/file.css */\n.mc5c717f39_file {\n    color: #fff\n}\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9hcHAvc3R5bGVzL3RoZW1lcy9kZWZhdWx0L2ZpbGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBLDRDQUFDO0FBQUQ7SUFDQyxXQUFZO0NBQ1oiLCJmaWxlIjoidG8uY3NzIiwic291cmNlc0NvbnRlbnQiOlsiLmZpbGUge1xuXHRjb2xvcjogI2ZmZjtcbn1cbiJdfQ== */',
  map: undefined,
  compositions:
   { 'src/app/styles/themes/default/app.css': { container: 'mc020e1dd7_container' },
     'src/app/styles/themes/default/file.css': { file: 'mc5c717f39_file' } } }
```

The `css` property only has the output from the `file.css` file, despite the `compositions` property having the output for `app.css` as well. The `result.opts.files` contains the files as also found in the `processor._files`.

Do you have any idea where I might be messing up, or if I maybe found a bug?

Once again I really like this package, thanks for all your efforts!

**Comment by tivac** [comment]
Approach 2 should definitely be the right approach, I'll look into why that isn't working.

Thinking about it more I think Approach 1 is pretty interesting though, if you explicitly re-process a file via the APIs it could be worth blowing up the cache for that file. I'll have to investigate and see what the bundlers do in terms of the API calls that happen when a file is seen more than once.

**Comment by chielkunkels** [comment]
Okay, good to know that I'm not an idiot haha. Thanks for looking into it. I did dig into it a bit but unfortunately I ran out if time.

Do let me know if I can be of any assistance!

**Comment by tivac** [comment]
No worries, I certainly appreciate the detailed bug report! I'll need to set up a repro and I've got a few other things going on atm but I'm hoping to get this tackled today.

**Comment by chielkunkels** [comment]
I get hom soon, more than happy to set up a repro repo for you :)

**Comment by chielkunkels** [comment]
Haha okay, you beat me to it, was just about to start!

**Comment by tivac** [comment]
I don't see your results in my test though, it's doing the right thing and generating output with the correct value. Probably worth having you create a repro, either via a standalone repo or a PR that adds a test like the one I tried to make.

**Comment by tivac** [comment]
If you want to chat about this a bit more synchronously I did do a thing recently.

[![Gitter](https://img.shields.io/gitter/room/modular-css/modular-css.svg)](https://gitter.im/modular-css/modular-css)

**Comment by tivac** [comment]
Ok so I investigated Approach 1 (when you re-add a file it automatically clears out the cache for that file) and it's problematic given how most of my tests are structured atm. There are lots of places where I do the following:

```js
Promise.all([
    processor.file("./packages/core/test/specimens/start.css"),
    processor.file("./packages/core/test/specimens/local.css")
])
.then(() => processor.output())
```

and if `start.css` references `local.css` (which it does) the test will fail because the inter-dependencies get blown up during all the async interactions. I don't know if that's a common real-world use-case but it seems like a dangerous footgun regardless.

I could **require** you to not call `.file`/`.string` until the previous one has finished, but I don't love that approach.

**Comment by chielkunkels** [comment]
Yeah, to be honest it does not seem worth the risk, and removing it is fine, it's just one extra call. I am unsure about the performance implications, but it seems like something that can be done later, rather than sooner.

On another note, I have created a repo with a reproduction of this issue, I hope it helps! https://github.com/chielkunkels/modular-css-324

**Comment by chielkunkels** [comment]
It just occurred to me that I should probably explain how to use the thing.

1. Clone it (duh :p)
2. `yarn install`
3. `./build`
4. Look at the output files `dist/public/assets/app.css` and `dist/styles.json`
5. It'll be watching, so if you update the `background` in `src/styles/one.css` you should see a bunch of output in the logs. Uf you check `dist/public/assets/app.css` again, you'll see it's missing the output from `one.css`

**Comment by tivac** [comment]
Ok, figured out the issue. We chatted about it in GitHub, but good to put here.

`processor.file()`/`processor.string()` return a promise, and you can **not** call `processor.output()` until those promises have resolved. It's a little unintuitive currently so I'm experimenting with removing that requirement (w/o an API change!) in the [output-after-resolve](https://github.com/tivac/modular-css/tree/output-after-resolve) branch.

It's currently very, very broken.

**Comment by tivac** [comment]
Turns out that isn't going to be possible, files are in the graph before they've finished processing and thus discovering all of the promises that need to be waited on is... complex.

Instead it's gonna reject the promise returned by `.output()` if any of the constituent files aren't done processing, which seems almost as useful.

**Comment by chielkunkels** [comment]
Yeah you would have to keep track of all the promises internally or something which is meh, rejecting on `.output()` definitely makes it very clear what's going wrong though - thanks!
