### ISSUE TITLE
Need a WebPack loader

### ISSUE THREAD

**Issue by tivac** [tivac/modular-css#34]
Because A) it'd be interesting to learn webpack and B) I'm sure it'll come in handy eventually.

**Comment by Morklympious** [comment]
https://github.com/webpack/css-loader 
Might be a good starting point if you're rolling your own!
(can't speak to how different it'll be since your implementation is stricter. Worth a look though.)

**Comment by ndelangen** [comment]
I saw you started a new branch for this, Do you think it's possible to aim for webpack 2?
https://webpack.js.org/

It's not formally released yet, but it doesn't look like it's going to be too long now.
