### ISSUE TITLE
Pre-fill m-css.com with samples that demonstrate the features of the lib

### ISSUE THREAD

**Issue by pygy** [tivac/modular-css#366]
It feels empty right now... I'd start with two files, one of which imports names from the other using `:external`, some `@value`, etc...

**Comment by darthmaim** [comment]
[There is already a prefilled one in the README](http://m-css.com/#W3sibmFtZSI6Ii8xLmNzcyIsImNzcyI6Ii8qIHNpbXBsZSB2YWx1ZXMgKi9cblxuQHZhbHVlIHJlZDogI0YwMDtcbkB2YWx1ZSBibHVlOiAjMDBGO1xuXG4uYSB7IGNvbG9yOiByZWQ7IH1cblxuLyogc2VsZWN0b3Igbm90IHJlbmFtZWQgKi9cbjpnbG9iYWwoLmIpIHsgYmFja2dyb3VuZDogd2hpdGU7IH1cblxuLyogTm90IG91dHB1dCBpbiBDU1MgYmVjYXVzZSBvbmx5IGNvbXBvc2VzICovXG4uYyB7IGNvbXBvc2VzOiBhOyB9XG4ifSx7Im5hbWUiOiIvMi5jc3MiLCJjc3MiOiJAdmFsdWUgKiBhcyBvbmUgZnJvbSBcIi4vMS5jc3NcIjtcblxuLyogaW1wb3J0IHZhbHVlcyBhcyBhIG5hbWVzcGFjZSAqL1xuLmEgeyBjb2xvcjogb25lLnJlZDsgfVxuXG4vKiBncmFiIHJlZmVyZW5jZSB0byBleHRlcm5hbCBzZWxlY3RvciBmb3Igb3ZlcnJpZGVzICovXG4uYiA6ZXh0ZXJuYWwoYSBmcm9tIFwiLi8xLmNzc1wiKSB7IGNvbG9yOiBvbmUuYmx1ZTsgfSJ9XQ==). Maybe just link to this on the website?

**Comment by tivac** [comment]
I should probably add some "Examples" UI which will pre-fill with some well-commented examples, and a "Reset" button of some kind to zero it all out.

Once there's a reset button I think defaulting to a small example showing some basic features is reasonable, I'll probably pattern most of it off of the [rollupjs REPL](http://rollupjs.org/repl).

**Comment by tivac** [comment]
This is handled in the basic case by the new site. There's an argument to be made about having a list of examples that can be loaded (& I'll get there eventually) but for now I'm closing this out
