### ISSUE TITLE
Investigate replacing pegjs with nearley

### ISSUE THREAD

**Issue by tivac** [tivac/modular-css#379]
https://nearley.js.org/

Smaller & faster parser code would be lovely.

**Comment by pygy** [comment]
From a quick look at your parsers, you could probably use RegExps instead.

https://github.com/pygy/compose-regexp.js helps for maintainability.

composes refs would need to be done in two passes though.

**Comment by tivac** [comment]
I find that having a real parser provides for better errors and much clearer specs/maintenance on the long run, plus I think they're fun to play with.

**Comment by pygy** [comment]
I love playing with parsers too, especially those based around the [PEG formalism](https://github.com/pygy/LuLPeg).

Good point regarding errors handling, that alone is indeed sufficient to pick a more advanced parser lib. What follows is for the sake of academic debate:

re. "real" parsers, RegExps are real parsers, of limited power (that would be sufficient for your grammars). re. spec/maintenance, that's the very point of RegExp combinators like compose-regexp... Regular grammars can be composed, but the RegExp syntax prevents abstraction.

Potential issues/improvements your parser code:

- You could add comments to your "whitespace" definition to have them supported everywhere.
- Your string definition doesn't handle escape sequences (in practice `\"`, `\'`, `\\n` could lead to problems and then if you support them you must also take care of `\\`).

**Comment by tivac** [comment]
This probably isn't worth it.
