### ISSUE TITLE
Question: Where is the css exported to?

### ISSUE THREAD

**Issue by thezimmee** [tivac/modular-css#433]
I apologize for asking a question that probably has a really simple answer, but I can't figure out how to use this. I import a CSS file, and it gives me an object so I can lookup the scoped class names:

```js
import css from './styles.css';
console.log(css);
// {
//   test: 'mc7e425961_test'
// }
```

But I can't find the actual styles. Where do I get the actual styles from for that selector? My use case is I would like to apply scoped selectors to templated markup, and be able to inject the css into style tags. This tool looks awesome, I just can't figure out how to use it correct. Any help is much appreciated!

P.S. I'm using the rollup plugin.

**Comment by tivac** [comment]
Are you using `rollup@0.60` or a previous version?

For rollup newer than `0.60` the CSS files corresponding to your JS bundles should land inside an `assets/` dir alongside the JS bundles.

For older versions of the plugin & rollup the CSS file should be wherever you configured the `css` property of the plugin to point to.

If you can share your rollup version, plugin version, and config I could probably offer you more specific help!

**Comment by thezimmee** [comment]
I am using the latest of both... I specifically upgraded rollup for this
plugin to 0.60.7 I believe for rollup and whatever the latest is for this
plugin. I'm running this plugin without any options, the rest of my config
is a little messy. Let me know if that helps, or if you need more than that
and I can send it when I'm at my computer.

On 6/20/18 at 4:03 PM, Pat wrote:

Are you using rollup@0.60 or a previous version?

For rollup newer than 0.60 the CSS files corresponding to your JS bundles
should land inside an assets/ dir alongside the JS bundles.

For older versions of the plugin & rollup the CSS file should be wherever
you configured the css property of the plugin to point to.

If you can share your rollup version, plugin version, and config I could
probably offer you more specific help!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tivac/modular-css/issues/433#issuecomment-398912358>,
or mute the thread

**Comment by tivac** [comment]
And you aren't seeing an `assets/` dir next to your `output.file` location?

**Comment by thezimmee** [comment]
Yes, I see it now. Thank you, I wasn't sure where to look. My question, now, is: can the actual css be imported to a JS file somehow, similar to the class names? Preferably as an object?

**Comment by tivac** [comment]
That's not something that is supported currently.

You could fork the rollup plugin to add that functionality but the `done` lifecycle would become useless.

**Comment by thezimmee** [comment]
I may eventually do that. Thank you for your help!
