### ISSUE TITLE
Random string in output filenames?

### ISSUE THREAD

**Issue by matthewgertner** [tivac/modular-css#440]
I'm assuming I'm missing something really obvious. My input JS is called `app.js` and I'm getting an output file called `app-6155e540.css`. I can't see any information in documentation that would explain why the name contains what appears to be a random string, and I don't know how to include the CSS in my HTML file without knowing how to predict the name. I also looked through the source code changes for the new Rollup API but so far I haven't found the part of the code that generates this random string.

**Comment by matthewgertner** [comment]
I tried including the CSS files in my HTML and the page is still not styled. Upon examination, the classnames have been dropped from all my elements. So if I have something like:

```
<div className={styles.div}>
```

It is simply output `<div>`. Clearly I have not migrated my config properly to the new version but I'm struggling to find any relevant information in the documentation. Here is my full Rollup config:

```
export default {
  input: 'src/index.js',
  output: {
    file: 'dist/app.js',
    format: 'iife'
  },
  moduleContext: {
    [require.resolve('whatwg-fetch')]: 'window'
  },
  watch: {
    include: ['src/**', 'styles/**'],
  },
  plugins: [
    { resolveId },
    copy({
      './resources/web': 'dist',
      './src/cordova.js': 'dist/cordova.js',
      './resources/general/fonts': 'dist/assets/styles/fonts',
      './resources/general/img': 'dist/img',
      verbose: true
    }),
    graphql(),
    modularCss({
      done: options.minify_css ? [autoprefixer, cssnano] : [autoprefixer],
      exportGlobals: false,
      include: '**/*.sss',
      parser: sugarss
    }),
    postCss({
      plugins: [],
      extensions: ['.styl'],
      inject: true
    }),
    babel({
      babelrc: false,
      exclude: [
        'node_modules/**',
      ],
      plugins: [
        !options.qa && ['remove-attribute', { attribute: 'data-qa' }],
        'transform-class-properties',
        'transform-object-rest-spread',
        'transform-runtime'
      ].filter(Boolean),
      presets: options.esnext_compatibility ? [['env', { modules: false }], 'react', 'stage-2'] : ['react'],
      runtimeHelpers: true
    }),
    commonjs({
      namedExports: {
        'node_modules/react/react.js': ['Children', 'Component', 'PropTypes', 'createElement'],
        'node_modules/react-dom/index.js': ['findDOMNode', 'render']
      }
    }),
    resolve({
      browser: true,
      jsnext: true
    }),
    replace({
      'process.env.AMPLITUDE_KEY': options.amplitude_key ? `"${options.amplitude_key}"`: null,
      'process.env.NODE_ENV': options.production_environment ? '"production"' : '""',
      'process.env.REDUX_LOGGING': options.redux_logging,
      'process.env.REQUEST_BASE_PATH': `"${options.request_base_path}"`,
      'process.env.VERSION': options.version
    }),
    options.minify_js ? uglify() : false,
    serve({
      contentBase: 'dist'
    })
  ]
}
```

**Comment by matthewgertner** [comment]
Just to clarify, we have been using React with the plugin like this:

```
import styles from 'styles.sss'

const Component = () => (<div className={styles.div} />)
```

This used to cause the `div` to get the appropriate `class` but now it is simply generated with no `class`.

**Comment by tivac** [comment]
It's part of the rollup asset API.

You'll want to set `output.assetFileNames`, here's what I use in the tests for stable output names.

https://github.com/tivac/modular-css/blob/6ce23fa8def8cf46a2c40b772b42d3397fae6c49/packages/rollup/test/rollup.test.js#L26

I don't know of an obvious reason why your components wouldn't be styled, can you provide an example repo I could poke at?

**Comment by tivac** [comment]
On my phone atm so can't deep link you, but it is documented on https://rollupjs.org/guide/en

I should better call it out in my docs though, sorry about this 😥

**Comment by matthewgertner** [comment]
Thanks. I'll have to put together a minimal test case which will probably lead to me finding the problem myself 😄 (must be an out-of-date package somewhere I guess, maybe Babel-related). I'll let you know.

**Comment by tivac** [comment]
@matthewgertner any progress on this?

**Comment by tivac** [comment]
Closing for now, feel free to re-open if this comes back up.
