### ISSUE TITLE
lodash.uniq dependency not included

### ISSUE THREAD

**Issue by balajisivanath** [tivac/modular-css#452]
![image](https://user-images.githubusercontent.com/2368442/42753140-951f6d8a-890d-11e8-814b-37ab093a4fee.png)
modular-css-core/plugins/composition.js:5:17

It seems like lodash.uniq dependency missed to be included in the build. (Using latest version v14)

**Comment by tivac** [comment]
Yikes, thanks. Working on a fix!

**Comment by tivac** [comment]
Fix released in `modular-css-core@14.0.1`, thanks again for the report!
