### ISSUE TITLE
[Core] Process files through "after" plugins in series?

### ISSUE THREAD

**Issue by deflock** [tivac/modular-css#503]
It seems that current Promise.all() implementation somehow affects on postcss' processor/plugins order:

```js
const results = await Promise.all(
    files.map((dep) => this._after.process(
        this._files[dep].result.root.clone(),
        
        params(this, {
            from : dep,
            to   : opts.to,
        })
    ))
);
```

I'm using a hybrid of `postcss-use`/`postcss-plugin-context` which changes postcss' plugins list at runtime.
`Before` plugins work as expected, but `after` are executed in some weird order.

If you think this change makes sense and you need more information, I'll try to investigate more and create a small reproduce repo with just `postcss-use`

**Comment by tivac** [comment]
I'm on mobile at the moment so unable to research. Could you more clearly state the issue with the after stage processing happening in an undefined order?

Doing it serially seems like it could slow down large builds by a lot so want to make sure I fully understand the issue!

**Comment by deflock** [comment]
Well, it's hard to describe, but I'll try.

```js
after: [
  (css, result) => console.log('1'),
  usePlugin({
    plugin2: (c, r) => console.log('2'),
    plugin3: (c, r) => console.log('3'),
    plugin4: (c, r) => console.log('4'),
  }),
]
```

This is how `postcss-use` works: in `use` plugin it remembers original plugins list, inserts new plugins in plugins chain and also pushes `use#reset` which restores the original list at the end of processing.

```css
/* a.css */
@use "plugin3";
@use "plugin4";

/* b.css */
@use "plugin2";
@use "plugin3";
@use "plugin4";
```

While processing `a.css` chain becomes:

- 1
- use
- 3
- 4
- use#reset

After processing `a.css` the chain should be restored to:

- 1
- use

This works in `before`, but in `after` `a.css`'s list is not restored and only `b.css`'s `use#reset` is executed. 
I'm not sure it's more clear now, also I need to investigate it more :)

**Comment by tivac** [comment]
Oh, yikes. If `postcss-use` is altering the postcss instance's `plugins` during execution that'd definitely explain why things are gross and broken when processing multiple async files simultaneously using `Promise.all`. 

`before` working make sense, it's applied during the dependency walk which is single-threaded and thus `before` is applied serially to files as they're walked.

Hrmm, I really don't love making `after` run serially but it may not be terrible. I have a reasonably large `modular-css` project at work I could test on to see how it effects overall build time.

**Comment by deflock** [comment]
It could be an Processor option if `after` should be processed serially or not?

**Comment by tivac** [comment]
I prefer to not add options which change flow like that, mostly to keep things simpler to reason about. 

Another idea which might be interesting is to see how expensive it'd be for each processor hook to create a new `postcss` instance per file. Then processing order wouldn't matter at all. I bet the more expensive bit is `require`-ing all the different plugins and stuff which we could still do up-front.

**Comment by deflock** [comment]
I thought that my complex setup somehow causes this issue, but here is a small reproduce repo https://github.com/deflock/modular-issue503 JFYI

**Comment by tivac** [comment]
What's the output I should be seeing if it's working?

I created a quick branch to test my "new postcss processor per file" idea, [`modular-css#postcss-per-file`](https://github.com/tivac/modular-css/compare/postcss-per-file) but when I run it against that repo I get a lot of hard-to-parse stuff out of it.

**Comment by deflock** [comment]
Right, it's a mess :)
There are 2 files `a.css` and `b.css` processed by `before` and `after` processors. Total 4 runs: first two is `before` (works correctly) and the last two is after. Now you can see for the first two: BEFORE, AFTER, RESTORED, BEFORE, AFTER, RESTORED, and for the last two: BEFORE, AFTER, BEFORE, AFTER, RESTORED.

**Comment by tivac** [comment]
Ok so using `after` against the branch I linked I get

```
BEFORE CHANGE
[ { [Function] postcssPlugin: 'plugin1', postcssVersion: '7.0.2' },
  { [Function] postcssPlugin: 'use', postcssVersion: '7.0.2' } ]
AFTER CHANGE
[ { [Function] postcssPlugin: 'plugin1', postcssVersion: '7.0.2' },
  { [Function] postcssPlugin: 'use', postcssVersion: '7.0.2' },
  { [Function] postcssPlugin: 'plugin3', postcssVersion: '7.0.2' },
  { [Function] postcssPlugin: 'plugin4', postcssVersion: '7.0.2' },
  { [Function] postcssPlugin: 'use#reset', postcssVersion: '7.0.2' } ]
BEFORE CHANGE
[ { [Function] postcssPlugin: 'plugin1', postcssVersion: '7.0.2' },
  { [Function] postcssPlugin: 'use', postcssVersion: '7.0.2' } ]
AFTER CHANGE
[ { [Function] postcssPlugin: 'plugin1', postcssVersion: '7.0.2' },
  { [Function] postcssPlugin: 'use', postcssVersion: '7.0.2' },
  { [Function] postcssPlugin: 'plugin2', postcssVersion: '7.0.2' },
  { [Function] postcssPlugin: 'plugin3', postcssVersion: '7.0.2' },
  { [Function] postcssPlugin: 'plugin4', postcssVersion: '7.0.2' },
  { [Function] postcssPlugin: 'use#reset', postcssVersion: '7.0.2' } ]
RESTORED
[ { [Function] postcssPlugin: 'plugin1', postcssVersion: '7.0.2' },
  { [Function] postcssPlugin: 'use', postcssVersion: '7.0.2' } ]
RESTORED
[ { [Function] postcssPlugin: 'plugin1', postcssVersion: '7.0.2' },
  { [Function] postcssPlugin: 'use', postcssVersion: '7.0.2' } ]
```

Which... seems correct to me. Haven't timed to see if it's substantially slower yet though.

**Comment by tivac** [comment]
The `BEFORE CHANGE`/`AFTER CHANGE`/`RESTORED` are still interleaved due to still using `Promise.all()`, but that's kinda the point. Since they've each got their own postcss instance everybody should still be cool & not messing with each others `.plugins`.

**Comment by deflock** [comment]
Are you sure separate processor per file will solve the problem? Every processor will hold the same plugin instances. When plugin depends on its internal state other processor+plugin pair can mutate this state

**Comment by tivac** [comment]
I verified that `postcss` will [create a new internal array of the plugins passed into it](http://api.postcss.org/processor.es6.html#line112) so at the very least things like `postcss-use` that manipulate that will be safe since they'll have their own `postcss` instance for each file.

Still unsure of the right approach here. Neither one of these approaches provides all that much protection against plugins doing gnarly things to other plugins or the processor as a whole.

**Comment by deflock** [comment]
Something like:

```js
let counter = 0;
(css, result) => {
  counter += 1;
  somethingAsync();
  console.log(counter);
  counter = 0;
}
```

If we have two processors, the first one will reset the counter and the second one will see incorrect zero value.

**Comment by tivac** [comment]
Decided running `after`s serially wasn't a big enough deal to avoid any longer, so just went for it. Thanks for the suggestion & the discussion @deflock, this was a fun problem to puzzle through!
