### ISSUE TITLE
Feature: camelCase

### ISSUE THREAD

**Issue by shiro** [tivac/modular-css#515]
`css-loader` has an option to convert dashes and underscores (or both) to camelCase *(see [options](https://github.com/webpack-contrib/css-loader#options))*

This allows us to use class names such as `.foo-bar` in css files without having to worry about js compatibility (having to worry about js in css doesn't seem logical).

Personally I like `css-loader`'s options API since it is rather intuitive and would recommend to use it as a reference, just my opinion though.

Also, migrating a huge existing codebase becomes near impossible.

*error message:*

```
Invalid JS identifier "upper-text", unable to export
warnings @ client:154
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
```

**Comment by tivac** [comment]
You can silence the errors by disabling the [`namedExports`](https://github.com/tivac/modular-css/blob/master/packages/webpack/README.md#namedexports) option. Auto-converting to camelCase is an interesting idea that I'd like to see a PR for.

**Comment by plesiecki** [comment]
Hello,

First of all great project and all its modules @tivac 
Especially, I'm pleasantly surprised with tree-shaked named exports. So much better than css-loader.

Back to the topic. It would be nice to have camelcased exports feature. Dash separated class names are bread and butter.

I'm happy to send a PR for this but first I would like to discuss the details.

Can't decide my self if this should be implemented in webpack loader or in postcss processor.

What do you think?

In the meantime I was able to hack postcss processor to overcome lack of this feature. It goes like this:
```js
const CSSPlugin = require("@modular-css/webpack/plugin");
const camelcaseKeys = require('camelcase-keys')

const plugin = new CSSPlugin({
//options
})
plugin.processor._process.plugins
    .push((_, result) => {
        result.messages
            .filter(({plugin}) => plugin === 'modular-css-composition')
            .forEach(payload => {
                payload.classes = camelcaseKeys(payload.classes)
            })
    })
```
@shiro Maybe you will find this useful.

**Comment by tivac** [comment]
This was fixed in [v26](https://github.com/tivac/modular-css/releases/tag/v26.0.0)
