### ISSUE TITLE
Varied casing in import paths result in differently generated class hashes

### ISSUE THREAD

**Issue by matthewrobb** [tivac/modular-css#527]
When importing a css file, if you use different casing in the import path you will end up with different classNames being generated for the imports.

Reproduction can be found here:
https://github.com/matthewrobb/repro-modular-css-rollup

**Comment by tivac** [comment]
This is due to the rollup plugin outputting chunks, so it accidentally sidesteps all of the dupe file detection & case-fixing logic.

Those should happen on file ingestion via the `string` method or `_walk`, ideally.
