### ISSUE TITLE
What is the correct way to handle css preprocessor?

### ISSUE THREAD

**Issue by kendrickw** [tivac/modular-css#550]
How can I incorporate css preprocessor into this plugin? (I'm using `packages/rollup`). 

For example, one of the css imports a stylus sheet (i.e. `abc.styl`).  Can I insert a stylus loader into the plugin, and have it transform the content of `abc.styl` into css, before having the plugin take over?

**Comment by tivac** [comment]
If there's a post CSS plugin for stylus you can add that to the `before` hook to have it transform that file into CSS.

**Comment by tivac** [comment]
Looks like https://github.com/Avol-V/postcss-stylus-parser is a thing that exists, but I don't think I expose a way to define the postcss `parser` value atm. I'll see what I can do to pipe that in.

**Comment by tivac** [comment]
Fix published in v21.2.0, you can pass a `postcss : { parser : ... }` option for parsing custom syntaxes.
