### ISSUE TITLE
Incorrect asset name when entry point name contains [hash]

### ISSUE THREAD

**Issue by kendrickw** [tivac/modular-css#560]
## Expected Behavior

Given the rollup config:
```js
// rollup.config.js
export default {
  input: {
     'dash-entry': 'src/entry.js'
  },
  plugins: [
    modularCss(),
    ...
  ],
  output: {
     entryFileNames: '[name].[hash].js',
     assetFileNames: '[name].[hash][extname]'
  },
};
```

Expect the generated css name to be `dash-entry.abababab.css`.

## Current Behavior
The generated css name is `entry.abababab.css` (missing `dash-`).
If I remove the `[hash]` from entryFileNames, then everything works as expected.
Also, if the input name doesn't have a '-', then the asset name is correctly generated as well.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `modular-css`  | 21.1.1 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.14.2 |

**Comment by tivac** [comment]
Almost certainly a bug in here:

https://github.com/tivac/modular-css/blob/7655d7250aa2afd887cf91102ac1b9dcb111847c/packages/rollup/parser.js#L13

Unfortunately I still don't think there's an easier way to get that info, so I'll have to add a failing test and work backwards.

**Comment by kendrickw** [comment]
Maybe something like this: 
```
[ "name",     "(?<name>^[\\w\\-. ]+)" ],
```
?

**Comment by tivac** [comment]
Working on a change to how assets are chunked/named that sidesteps this problem by naming them after the CSS file, not the JS entry file. It's just too painful to try and figure out with the info rollup currently gives me.

Working on that over here, almost done: https://github.com/tivac/modular-css/tree/corrected-chunking
