### ISSUE TITLE
Call toString on invalid composes reference

### ISSUE THREAD

**Issue by bryanant** [tivac/modular-css#578]
Error handling on invalid references doesn't currently spit out useful data.  It would be really nice to be able to see the actual problem point where a composition is found to be invalid (at the very least the line of the file that causes the issue).

**Comment by tivac** [comment]
For reference, here's what [the REPL](https://m-css.com/repl/#NrBEHoFsEMEsDsB0BjAzq0AaCAqABABICmATkQOSp6oD2kR1skADgDYNEAe0L7VALjTwBzIvzwBPGgFdq-aCX5EAJgEI8OcAB14O8PgDKRdskEk8B5DWYJhG7UgBmNGsOh4A3niusaJAFx4ZMoA3HgAvjp6hsZEpn7edMw0qLD8sDTw9jqIAEYubp46eCWJLClEqIHOriHFpfUludDIANbCJDLwyoG5rNJEdfCRuvD6eABq0P2V2fAAAgBu0wN4jsIAwjS+ASJkRPBDOQDuBe4ejYk71ZvbfkMjoAC6T0A) shows using the error objects returned from `modular-css` (via `postcss`) directly.



```
CssSyntaxError: modular-css-composition: /main.css:8:15: Invalid composes reference

   6 | /* Selector composition */
   7 | .booga {
>  8 |     composes: foog;
     |               ^
   9 |     
  10 |     background: blue;
```
