### ISSUE TITLE
true-case-path is slowing down builds, try async

### ISSUE THREAD

**Issue by Ryan-McMillan** [tivac/modular-css#581]
In lib/normalize.js, true-case-path appears to be adding a lot of time to builds.  We discussed exploring if the async version of this helps.

Build times decrease significantly when bypassing true-case-path 🎉 
first time: 15s -> 10s
incremental builds: 3.3s -> 2.2s

| `modular-css/rollup`  | 23.0.6 |
| `modular-css/processor` | 23.0.4 |
| `npm --version`  | 6.9.0 |
| `node --version` | 10.15.3 |

| Windows | 10 |

**Comment by tivac** [comment]
Removing this and adding a warning instead in [this branch](https://github.com/tivac/modular-css/tree/async-normalize)
