### ISSUE TITLE
CLI API missing 'imports' module in cli.js?

### ISSUE THREAD

**Issue by Morklympious** [tivac/modular-css#70]
I'm unable to execute `$ modular-css` on the command line without being met with a 'command does not exist' error. 

I've installed it both locally and globally. I tested the `browserify` command (both local/global also) in the same project as modular-css to make sure commands are actually getting through. `browserify` returns its options list, but `modular-css` gives me guff. 

Interesting enough, and this might be related, making a `node` call to their respective bin files:

`$ node node_modules/browserify/bin/cmd.js` Returns the browserify options list. 

`$ node node_modules/modular-css/bin/cli.js` Returns an error:
`Error: Cannot find module '../imports'`

Obviously I don't know if you've omitted `imports` intentionally, but from what I'm seeing, I assume postCSS is the `.process()` command? Anyways! I'm trying to get a simple `modular-css ./entry.css ./output.css` (or even just output to stdout) working. I've replicated it on both Mac and PC. Anything I might be missing here?

**Comment by tivac** [comment]
`package.json` doesn't have a `bin` field, so npm isn't generating the alias. I'll fix that.

The `Cannot find module '../imports' is bit-rot in the CLI, I'll fix that too.

**Comment by Morklympious** [comment]
Just learned about the `bin` field bit. Gotta write me a CLI app one of these days. Awesome! Thank you kindly!

**Comment by tivac** [comment]
Fix merged to master, publishing `0.10.4` here momentarily

**Comment by tivac** [comment]
@Morklympious After a bit of flopping around `modular-css@0.10.6` is on NPM w/ these fixes.

**Comment by Morklympious** [comment]
:+1: :+1: :+1:
