### ISSUE TITLE
SCSS :global issue

### ISSUE THREAD

**Issue by RobMayer** [tivac/modular-css#705]
## Expected Behavior
`:global(.button) {
   background: red;
   &.other_class {
      border-color: blue;
   }
}`

should output 
`.button { background: red }
.button .hash_other_class { border-color: blue; }`

## Current Behavior
seems to barf (cannot read property root of undefined) - uncertain the root (hah) cause...
does not barf when using non-global classes as root for nested classes.

## Context
Using web-pack, if that's relevant. I know you're not a webpack user, so I'm totally okay with helping with troubleshooting if I can get better direction than root is undefined >.<

**Comment by RobMayer** [comment]
``
｢wdm｣: Compiling...
× ｢wdm｣: TypeError: Cannot read property 'root' of undefined
    at Processor.output ([redacted]\node_modules\@modular-css\processor\processor.js:253:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
``

**Comment by RobMayer** [comment]
Oh crap - please disregard... turns out there was a problem with one of my imports that only manifested when I nested a global class...

**Comment by tivac** [comment]
@RobMayer would you be willing to share a small example of the problematic CSS? Even if you figured out your issue it'd be good for the lib to handle that more gracefully.
