### ISSUE TITLE
Assumes import Link from 'components/link' is same as <link> tag in /svelte package

### ISSUE THREAD

**Issue by destructobeam** [tivac/modular-css#711]
When preprocessing a .svelte file, compiling errors due to seeing a Link component import/tag as a <link> tag. Whatever is throwing this error probably needs to be case sensitive, as I would think that is a pretty common import/component name.

## Example to reproduce
```svelte
<script>
  import Link from './link'; // Doesnt' matter what is in this component, error is on import.
</script>

<Link />

<style>
   /* Need a style block to throw incorrect conflict error between <style> and <link> tags */
  .something { }
</style>
```

## Expected Behavior
Should work without errors.

## Current Behavior
Compile errors warning 

## Possible Solution
Change regex or whatever to case sensitive.

Sorry for not filling out everything, looking at other solutions atm, just letting you know, hopefully to help.

Cheers.

**Comment by tivac** [comment]
This is released in `@modular-css/svelte@25.6.0`
