### ISSUE TITLE
Support value renaming?

### ISSUE THREAD

**Issue by jquense** [tivac/modular-css#719]
### Feature Use Case

css-modules allows `@value foo as localFoo from './colors.css'`, which is nice for avoiding namespace conflicts. Was there a specific reason this wasn't brought over, or is it more of a complexity issue?

### Feature Proposal

Maybe add support?

**Comment by tivac** [comment]
Probably got missed because I've never used that functionality. I'm always open for PRs, or I can take a look at some point here.

**Comment by jquense** [comment]
I can take a look, I'm not sure if it's worth it given m-css support for value namespace imports, tho. let me think a bit on it

**Comment by tivac** [comment]
This is released in `@modular-css/core@25.6.0`
