### ISSUE TITLE
Editor support 

### ISSUE THREAD

**Issue by erykpiast** [tivac/modular-css#726]
How do you work with Modular CSS in common code editors / IDEs like VSCode or WebStorm? Particularly, how do you manage `composes` of multiple declarations?
```
.foo {
  composes: bar, baz from '@my/ui-framework';
}
```

## Expected Behavior
I'd like my editor to understand composes syntax as valid. That means:
 * proper syntax highlighting (different colors for tokens like `from` keyword and class names)
 * recognizing string after `from` keyword as a file reference, validating its presence on the filesystem and auto-completing them
 * recognizing strings before `from` keyword as class names, validating its presence in the source file and auto-completing them

## Current Behavior
VSCode does nothing from the list above. 

![Screenshot 2020-02-19 at 10 44 30](https://user-images.githubusercontent.com/1434406/74823788-951fff00-5307-11ea-8c09-eff77f9429ad.png)

Neither does WebStorm.
![image](https://user-images.githubusercontent.com/1434406/74823877-bbde3580-5307-11ea-898e-909ec05fae44.png)

## Possible Solution
1. Custom editor plugin
2. Change in grammar to align with more popular solutions, like [Webpack's css-loader](https://github.com/webpack-contrib/css-loader). At least WebStorm works well with that.
```
.foo {
  composes: bar from '~@my/ui-framework';
}
```

## Context
I try to have a development environment as comfortable as possible, like for JavaScript or CSS Modules.

## Your Environment
VSCode 1.42.1

| Executable | Version |
| ---: | :--- |
| `modular-css`  | 25.3.1 |
| `npm --version`  | 6.13.7 |
| `yarn --version` | - |
| `node --version` | 12.4.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Catalina | 10.15.3 |

**Comment by tivac** [comment]
We tend to use stylelint for validation, and so use the [`@modular-css/stylelint-config`](https://www.npmjs.com/package/@modular-css/stylelint-config) package to help configure it correctly to at least not lose its mind on the custom syntax bits.

I don't have time or a particularly strong need to add custom editor extensions to better highlight the custom syntax. If you'd like to do that work I'd love to see a PR adding it.

It looks like there's a [CSS Modules extension](https://marketplace.visualstudio.com/items?itemName=clinyong.vscode-css-modules) for vscode already which does something similar for base CSS Modules (only in React projects though?) and it is [on Github](https://github.com/clinyong/vscode-css-modules) if you wanted to use that as a starting point.

**Comment by erykpiast** [comment]
Alright! Thank you for the answer :)

The extension you've linked is not exactly what I think about. It provides auto-completion for class names in JavaScript modules, I'd like to have it **inside CSS**. So basically it should be an extension of regular CSS grammar. So I'd start rather from [vscode-css-languageservice](https://github.com/microsoft/vscode-css-languageservice/tree/master/src). But, to be honest, I know nothing about adding language support to editors. I have no idea if I need a code action, completion or navigation service. Or maybe all of them? :D I'll appreciate some help.

For validating if the class names on JS side I use TypeScript typings generated by a slightly modified version of [css-modules-typescript-loader](https://github.com/seek-oss/css-modules-typescript-loader) (unfortunately it's an internal project, I could put pressure on open-sourcing it).

**Comment by tivac** [comment]
I don't have any experience writing a vscode language service either I'm afraid, just trying to help get you pointed towards things that might help.

**Comment by jquense** [comment]
We use https://github.com/AndrewLeedham/vscode-css-modules, it also has instructions for configuring vscode's builtin lint plugins to handle the syntax.

**Comment by tivac** [comment]
Huh, that same developer also has one specifically for `modular-css`.

https://github.com/AndrewLeedham/vscode-modular-css

Gonna try that out since I'm setting up a brand-new vscode install today anyways.

**Comment by erykpiast** [comment]
@tivac Somehow I missed this one. It looks great, thanks! For some reason, I cannot make imports working, though. Could you try the plugin and tell if `Go to reference` feature works for you (for the file referenced inside `composes`)?
