### ISSUE TITLE
rollup-plugin-postcss is not working anymore when modullar-css in used

### ISSUE THREAD

**Issue by ionutcirja** [tivac/modular-css#735]
In my project I'm using postcss especially for global imports.
When  I added modular-css, postcss stopped working. The exported global css file contained just "default export {}"

**Comment by tivac** [comment]
I have good news and bad news for you.

Bad news first, I suspect there's no way to get `rollup-plugin-postcss` and `@modular-css/rollup` to play nicely together, they're both going to try and process any `.css` file in the bundle and whichever is defined first in your `rollup.config.js` file will win.

The good news is that for what you're asking for you don't need `rollup-plugin-postcs`. `modular-css` already uses postcss, and includes [several hooks](https://m-css.com/api/#extending) that you can use to add custom postcss plugins to run at various points in the processing lifecycle. Update your `@modular-css/rollup` config to include one of the hooks and add your postcss plugin to the array and you should be good.

**Comment by ionutcirja** [comment]
That's great news actually. Many thanks for your help.
