### ISSUE TITLE
Composes doesn't work in rollup with scss

### ISSUE THREAD

**Issue by witcher-development** [tivac/modular-css#743]
## Expected Behavior
Compile composes to corresponding styles.

## Current Behavior
Composes is ignored

## Possible Solution
I'm not sure if I use the plugin in the right sequence with scss one.

## Steps to Reproduce (for bugs)
If the issue will be not in configs, then I will try to share the code. Hope screenshots will be sufficient.

`rollup config`
![image](https://user-images.githubusercontent.com/28788017/78398241-6af67800-75fb-11ea-8ae4-8da52b34e424.png)

`scss input`
![image](https://user-images.githubusercontent.com/28788017/78398271-7649a380-75fb-11ea-941f-8e8382fd1ae9.png)

`css output`
![image](https://user-images.githubusercontent.com/28788017/78398294-82cdfc00-75fb-11ea-8d6e-5f7e9bca768a.png)

I've tried to mix configs in different orders, but it didn't help.

## Context
I'm working on a chrome devtools extension project. I've been facing many problems with the ecosystem in this field in development process. I've already participated in extending `rollup-plugin-chrome-extension` and would be glad to bring a benefit here if will be needed.

## Your Environment
Chrome extension, rollup, typescript, scss

Versions:

| `rollup`  | 2.2.0 |
| `modular-css`  | 25.5.0 |
| `npm --version`  | 6.13.7 |
| `node --version` | v10.16.3 |

| Ubuntu | 19.10 |

**Comment by tivac** [comment]
`@rollup/modular-css` defaults to `*.css` as a filter, so it likely doesn't know to process your `.scss` files.

Would you try providing an [`include`](https://m-css.com/api/#rollup) filter of `*.scss` and see if that helps? If it doesn't I'll likely ask you to provide a repo so this can be investigated further.

**Comment by witcher-development** [comment]
Hello!
Unfortunately, it didn't help. In fact, I thought that if I set `css()` after `scss()` in plugins order then it will work as a pipeline and css plugin will receive a css bundle from the scss one.
But any way I'm going to talk with team and share the project somehow. Will back soon, thanks!

**Comment by witcher-development** [comment]
Well, I tried to reproduce the issue in an empty project with\without scss, but faced that something is going wrong even without scss. I'm almost sure that I have been mixing up something with configs.
https://github.com/witcher-development/test-css-modules-rollup

**Comment by tivac** [comment]
@witcher-development it's because your `index.js` doesn't actually reference the `.css` file's exports, so it gets tree-shaken.

Changing `index.js` to this:

```js
import css from './style.css';

console.log(css);
```

results in the correct output.

**Comment by tivac** [comment]
`rollup-plugin-scss` and `@modular-css/rollup` are going to be fundamentally incompatible though, because they both expect to match imports of `.css` files and then convert them into JS output. That means that when the next plugin comes along and tries to process the `.css` file it's not actually CSS any more and the plugin doesn't know what to do with it.

You could probably put something together using `postcss-scss`, but out of the box they're just not going to play well together.

**Comment by witcher-development** [comment]
@tivac 
Okay, I got it. I've decided to use scss @extend, for now, to make this works.
Anyway thanks for the response!
