### ISSUE TITLE
modular-css/svelte tries to parse pages that are not css files

### ISSUE THREAD

**Issue by tanishalfelven** [tivac/modular-css#764]
When erroneously importing a file from a svelte file, it was discovered that if the imported file is not a css file then the parser horks on the file and it can be difficult to tell what is going on.

Expected behavior is a giant error should level back to the user explaining that a non-css file was imported and failed to parse.

**Comment by tivac** [comment]
Fixed in #766 but not released yet.

**Comment by tivac** [comment]
Released in 25.8.0
