### ISSUE TITLE
@modular-css/svelte errors when classes get more descriptive through page

### ISSUE THREAD

**Issue by tanishalfelven** [tivac/modular-css#780]
https://github.com/tivac/modular-css/blob/main/packages/svelte/svelte.js#L207
if you have a class that is similar to a different css class occuring after the original in markup then there is a big explosion.
Fine:
```js
<div class="{css.someclass}"/>
<div class="{css.some}"/>
```

Error:
```js
<div class="{css.some}"/>
<div class="{css.someclass}"/>
```

**Comment by tivac** [comment]
Fixed by 1ac9af5f1bf679e677b6fd1e7631802d3db56551!
