### ISSUE TITLE
Docs Repl broken

### ISSUE THREAD

**Issue by zachwolf** [tivac/modular-css#796]
## Expected Behavior
Not 100% sure, but I assume something similar to https://babeljs.io/repl

## Current Behavior
Visiting https://m-css.com/repl/ displays empty state with console error.

```
rule.js:16 Uncaught (in promise) TypeError: Cannot read property 'prototype' of undefined
    at rule.js:16
    at rule.js:29
    at ke (browser.js:195)
    at list.js:92
```

![Screen Shot 2021-07-16 at 3 27 13 PM](https://user-images.githubusercontent.com/606237/126005588-3b4e554b-5590-4693-b19d-9bdd0e023d7a.png)

## Your Environment

| Executable | Version |
| ---: | :--- |
| `modular-css`  | VERSION |
| `npm --version`  | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| macOS Catalina | 10.15.7 |
| Chrome | 91.0.4472.114 |
| Safari | 14.0.3 |

**Comment by tivac** [comment]
Thanks for the reminder, looks like it's working again now after some package updates and general tidying up.
