### ISSUE TITLE
ParseError when trying to bundle both via build script and CLI

### ISSUE THREAD

**Issue by Morklympious** [tivac/modular-css#92]
Hey!

So I ran into something odd, and I say that because last time I used `modular-css` through a build file with `browserify` it took just fine, but now I'm running into parse errors:

The build file I'm trying to run is:

````js
var fs         = require('fs'),
    path       = require('path'),
    browserify = require('browserify');

var build = browserify("./src/entry.js");

build.plugin("modular-css", {

    // Output CSS file with all of your fancy scoped classes.
    css : "../dist/css/site.css"

});

build.bundle(function(err, output) {

  if(err) console.log(err);

  var write = fs.writeFileSync,
      join  = path.join;


  write(join(__dirname, '../dist/bundle.js'), output);
});
````

`entry.js` contains a reference to a `.css` file via `require`:
````js
var example = require('./js/example');
var css     = require('./css/global.css'); // WHY DO YOU HATE ME. 

global.example = example;

example.write('Writing in the console.')

````

 what I expect to happen is for browserify to use the plugin to recognize the `.css` file and HANDLE it, instead, a lot of what I'm getting in my console when I try to run this file is:

````bash
C:\Users\Morklympious\Desktop\development\stackpack\src\css\global.css:2
div {
    ^
ParseError: Unexpected token
````

"What am I doing wrong? Am I some kind of dingus?" I think to myself as I try to build this damn thing for the tenth time. I check the docs. Then I check the docs again.

I ran your CLI example in the command line (with appropriate paths swapped)
`browserify -p [ modular-css --css './dist/css/site.css' ] ./src/entry.js -o ./dist/bundle.js`
`browserify -p [ modular-css --css './dist/css/site.css' ] ./src/entry.js`

Both of these lead to the same Parse error in the cli. 

Is there anything I'm missing here? I don't think I'm misusing the plugin in my build file, but I figure I should get your eyes on it in case it's symptomatic of a bigger problem other than "I'm tired and getting nerd-sniped"

Any help is appreciated! Thanks! :D

**Comment by tinchoz49** [comment]
I think there was a breaking change using modular-css as a browserify plugin.

The updated correct syntax is: 

```js
build.plugin("modular-css/browserify", {

    // Output CSS file with all of your fancy scoped classes.
    css : "../dist/css/site.css"

});
```

I remember seeing this syntax explained in the readme but now is gone :s

**Comment by Morklympious** [comment]
@tinchoz49 That solved it for the buildfile portion, which is what I wanted more. Thanks! :+1:  Is there any syntax change as it relates to the CLI usage? Do you know?

**Comment by tivac** [comment]
In `0.12.x` it was changed so that the browserify plugin was no longer the default export, because the intent is to have multiple bundlers supported. I dunno how that got missed in the readme though, ugh.

Use `modular-css/browserify` instead, both in a build script or on the CLI.

**Comment by tivac** [comment]
Note: until this project hits `1.0.0` the minor version should be used as a guide for whether a release contains breaking API changes.

**Comment by Morklympious** [comment]
Noted! Thanks!
