### ISSUE TITLE
Modular-CSS not working with latest Rollup v3

### ISSUE THREAD

**Issue by balajisivanath** [tivac/modular-css#940]
### Describe the bug

It seems that latest modular-css is not compatible with the latest version of Rollup 3.20.2. Could you please investigate this issue?
<img width="471" alt="image" src="https://user-images.githubusercontent.com/2368442/229003117-c03096e5-eda2-42df-a57a-23038f129e07.png">

### Reproduction

1. Install rollup latest version
2. Install modular-css latest version

### System Info

```shell
## Binaries:
 - Node: 16.13.2 - /usr/local/bin/node
 - npm: 9.6.0 - /usr/local/bin/npm
## npmPackages:
 - @modular-css/rollup: ^29.0.0 => 29.0.0
 - rollup: ^3.20.2 => 3.20.2
```

### Severity

blocking an upgrade

**Comment by tivac** [comment]
Thanks! Should be fixed with `@modular-css/rollup@29.0.1`
